/*

#align(center, box(width: 60%, tablex(
	fill: (col, row) => if col == 0 or row == 0 {black} else {white},
	columns: (0.5fr, 1fr, 1fr, 1fr, 1fr),
	align: center + horizon,
	stroke: 0.2mm,

	[], text(fill: white)[\[15:12\]], text(fill: white)[\[11:8\]],
	text(fill: white)[\[7:4\]], text(fill: white)[\[3:0\]],
	text(fill: white)[Bs/Bl], colspanx(2)[Opc.\[7:0\]], [Src.], [Dst.],
	text(fill: white)[Us], colspanx(2)[Opc.\[7:0\]], [Imm.\[3:0\]], [Dst.],
	text(fill: white)[Ul], [Opc.\[3:0\]], colspanx(2)[Imm.\[7:0\]], [Dst.],
	text(fill: white)[N], colspanx(2)[Opc.\[7:0\]], [Imm.\[3:0\]], [Imm.\[7:4\]],
)))

#align(center, table(columns: 4, rows: 17,
	fill: (_, row) => if row == 0 {black} else {white},
	text(fill: white)[*Arch. Name*],
	text(fill: white)[*Conv. Name*],
	text(fill: white)[*Description*],
	text(fill: white)[*Conv. Saving*],
	[x0], [\$zr], [Constant Zero], [None],
	[x1], [\$at], [Assembler Temporary], [Caller],
	[x2], [\$rp], [Return Pointer], [Caller],
	[x3], [\$a0], [Arg./Return Value \#0], [Caller],
	[x4], [\$a1], [Arg./Return Value \#1], [Caller],
	[x5], [\$a2], [Arg./Return Value \#2], [Caller],
	[x6], [\$t0], [Temporary Value \#0], [Caller],
	[x7], [\$t1], [Temporary Value \#1], [Caller],
	[x8], [\$t2], [Temporary Value \#2], [Caller],
	[x9], [\$s0], [Saved Value \#0], [Callee],
	[xA], [\$s1], [Saved Value \#1], [Callee],
	[xB], [\$s2], [Saved Value \#2], [Callee],
	[xC], [\$s3], [Saved Value \#3], [Callee],
	[xD], [\$s4], [Saved Value \#4], [Callee],
	[xE], [\$s5], [Saved Value \#5], [Callee],
	[xF], [\$fp], [Frame Pointer], [Callee],
))

#align(center, table(columns: 4, rows: 17,
	fill: (_, row) => if row == 0 {black} else {white},
	text(fill: white)[*Arch. Name*],
	text(fill: white)[*Conv. Name*],
	text(fill: white)[*Description*],
	text(fill: white)[*Conv. Saving*],
	[y0], [\$t3], [Temporary Value \#3], [Caller],
	[y1], [\$t4], [Temporary Value \#4], [Caller],
	[y2], [\$t5], [Temporary Value \#5], [Caller],
	[y3], [\$a3], [Arg./Return Value \#3], [Caller],
	[y4], [\$a4], [Arg./Return Value \#4], [Caller],
	[y5], [\$a5], [Arg./Return Value \#5], [Caller],
	[y6], [\$s6], [Saved Value \#6], [Callee],
	[y7], [\$s7], [Saved Value \#7], [Callee],
	[y8], [\$s8], [Saved Value \#8], [Callee],
	[y9], [\$s9], [Saved Value \#9], [Callee],
	[yA], [\$gp], [Global Pointer], [Callee],
	[yB], [\$sp], [User Stack Pointer], [Callee],
	[yC], [\$k0], [System Value \#0], [Callee],
	[yD], [\$k1], [System Value \#1], [Callee],
	[yE], [\$k2], [System Value \#2], [Callee],
	[yF], [\$kp], [System Stack Pointer], [Callee],
))
